const palavras = [
  "abrir", "abuso", "acaso", "aceso", "achar", "acima", "acolá", "açude", "adeus", "adiar",
  "advir", "afago", "afeto", "afins", "afora", "ágape", "agora", "agudo", "ainda", "ajuda",
  "alado", "álamo", "álbum", "alçar", "algoz", "algum", "aliás", "álibi", "aluno", "amado",
  "âmago", "âmbar", "ambos", "ameno", "amigo", "amplo", "anais", "andar", "anelo", "anexo",
  "ânimo", "ânsia", "antes", "antro", "anuir", "apear", "apego", "apelo", "ápice", "apoio",
  "apraz", "aquém", "arado", "arcar", "ardil", "ardor", "árduo", "areia", "arfar", "árido",
  "aroma", "arroz", "asilo", "assar", "assaz", "astro", "átimo", "ativo", "átomo", "atrás",
  "átrio", "atroz", "atual", "atuar", "audaz", "áudio", "áureo", "autor", "avaro", "avião",
  "aviar", "ávido", "aviso", "axial", "axila",
  "baixo", "banal", "bando", "banto", "banzo", "barão", "barro", "bater", "bazar", "beato",
  "bedel", "beijo", "berro", "besta", "bicho", "bioma", "birra", "blasé", "boato", "boçal",
  "bolsa", "bolso", "bônus", "botar", "brabo", "brado", "bravo", "brega", "breve", "briga",
  "brisa", "bruma", "bruto", "bruxo", "bucho", "bugre", "bulir", "burro", "busca",
  "cabal", "caber", "caçar", "cacho", "cacto", "caixa", "calão", "calça", "calda", "calmo",
  "calor", "calvo", "campa", "campo", "canil", "cânon", "canto", "capaz", "cardo", "cargo",
  "carma", "carro", "carta", "casal", "casar", "casta", "casto", "catre", "cauda", "causa",
  "ceder", "cenho", "censo", "cerca", "cerne", "certo", "cesta", "cetro", "chaga", "chama",
  "chato", "chave", "chefe", "cheio", "choça", "chulo", "chuva", "ciclo", "cifra", "cinto",
  "cioso", "cisão", "cisma", "citar", "ciúme", "cível", "civil", "claro", "clava", "clean",
  "clero", "clima", "close", "coçar", "cocho", "coeso", "coevo", "coisa", "coito", "combo",
  "comer", "comum", "conta", "conto", "cópia", "coral", "corar", "corja", "coroa", "corpo",
  "corso", "corte", "coser", "cosmo", "cover", "covil", "cozer", "credo", "criar", "crime",
  "crise", "crivo", "cruel", "culpa", "culto", "cunho", "curso", "custo", "cútis",
  "dança", "débil", "deixa", "demão", "dengo", "denso", "depor", "deter", "dever", "devir",
  "diabo", "digno", "dizer", "dócil", "dogma", "doido", "doído", "dorso", "drama", "dúbio",
  "ébano", "ébrio", "ecoar", "égide", "elite", "enjoo", "então", "épico", "época", "ereto",
  "esgar", "estar", "etapa", "ética", "ético", "etnia", "exame", "exato", "êxito", "êxodo",
  "expor", "extra",
  "facho", "fácil", "faina", "faixa", "falar", "falha", "falso", "falta", "fardo", "farol",
  "farpa", "farsa", "farto", "fatal", "fator", "fátuo", "fauna", "favor", "fazer", "feito",
  "feixe", "feliz", "fenda", "ferir", "feroz", "festa", "feudo", "ficar", "ficha", "filho",
  "final", "findo", "firma", "firme", "fitar", "fixar", "flora", "fluir", "fluxo", "folga",
  "folha", "folia", "fonte", "força", "forma", "forro", "forte", "fórum", "fossa", "fosso",
  "fraco", "frase", "frota", "fruir", "fruto", "fugaz", "fugir", "fundo", "furor", "fusão",
  "fútil",
  "gabar", "garbo", "gemer", "gênio", "genro", "gente", "geral", "gerar", "gerir", "gesto",
  "gíria", "golpe", "gosto", "graça", "grama", "grato", "grave", "grupo", "gueto", "guisa",
  "hábil", "harém", "haste", "haver", "havia", "herói", "hiato", "hífen", "hobby", "homem",
  "honra", "horda", "horto", "hoste", "humor",
  "ícone", "ideal", "ideia", "ídolo", "idoso", "ígneo", "igual", "ileso", "ímpar", "ímpio",
  "impor", "imune", "inato", "índio", "invés", "irado", "irmão", "itens",
  "jazer", "jeito", "jejum", "jogar", "jovem", "judeu", "juízo", "junco", "junto", "justo",
  "lábia", "labor", "laico", "lápis", "lapso", "largo", "lasso", "laudo", "lavra", "lazer",
  "legal", "légua", "leigo", "leite", "leito", "lenda", "lento", "lesão", "letal", "letra",
  "levar", "lição", "lidar", "líder", "ligar", "limbo", "limpo", "lindo", "linha", "livre",
  "livro", "local", "logro", "longe", "longo", "louça", "louco", "louro", "lousa", "lucro",
  "lugar", "lutar",
  "macho", "macio", "macro", "magia", "mágoa", "maior", "malta", "mamãe", "manga", "manha",
  "manhã", "mania", "manso", "manto", "marca", "marco", "massa", "matiz", "medir", "meigo",
  "mente", "mesmo", "mexer", "mídia", "mimar", "minar", "míope", "misto", "moção", "mocho",
  "modal", "molde", "molho", "monge", "monta", "monte", "moral", "morar", "morfo", "morro",
  "mosto", "motim", "móvel", "mover", "mudar", "muito", "mundo", "museu", "mútuo", "nação",
  "nácar", "narco", "nariz", "natal", "navio", "negar", "negro", "neném", "nesga", "nicho",
  "nível", "nobre", "noção", "nódoa", "noite", "norma", "nunca", "nuvem", "oásis", "óbice",
  "óbito", "obter", "óbvio", "ocaso", "odiar", "olhar", "olhos", "ontem", "opaco", "opção",
  "optar", "ordem", "órfão", "órgão", "ornar", "ótica", "ótimo", "ousar",
  "outro", "ouvir", "pacto", "pagão", "pagar", "paiol", "pajem", "papel", "parar", "parco",
  "pardo", "páreo", "pária", "parte", "parvo", "pasmo", "passa", "passe", "pauta", "pavor",
  "pecha", "pedir", "pedra", "pegar", "peito", "peixe", "penca", "penso", "penta", "perco",
  "perda", "perto", "pesar", "peste", "piada", "piche", "pífio", "pilar", "pinho", "pique",
  "pisar", "plano", "platô", "plebe", "pleno", "pluma", "pobre", "podar", "poder", "pódio",
  "poema", "poeta", "pólis", "pomar", "pompa", "ponto", "porca", "porta", "porte", "posse",
  "posto", "pouco", "prado", "praga", "praia", "praxe", "prazo", "prece", "preço", "presa",
  "preso", "preto", "privê", "probo", "prole", "prosa", "prova", "prumo", "puder", "pudor",
  "pulha", "puxar", "quase", "queda", "quiçá", "quota", "rádio", "raiva", "ranço", "rapaz",
  "razão", "redor", "refém", "reger", "régio", "regra", "reino", "reler", "reles", "relva",
  "remir", "renda", "rente", "repor", "resto", "reter", "rever", "revés", "rezar", "rigor",
  "risco", "riste", "ritmo", "rival", "rocha", "rogar", "roupa", "rubro", "ruído", "ruína",
  "rumor", "rural", "saber", "sabiá", "sábio", "sabor", "sadio", "sagaz", "saída", "saldo",
  "salmo", "salva", "salve", "samba", "sanar", "santo", "sarau", "sarça", "saúde", "seara",
  "seção", "seita", "seiva", "seixo", "selar", "senão", "senda", "senil", "senso", "serão",
  "série", "sério", "servo", "sesta", "setor", "sexta", "sigla", "signo", "silvo", "símio",
  "sinal", "sinhá", "sinto", "sítio", "sobre", "soldo", "solto", "sonho", "sonso", "sorte",
  "sósia", "sótão", "suave", "subir", "súcia", "sugar", "sulco", "sumir", "super", "supor",
  "supra", "surto", "sutil", "tacha", "tanto", "tarde", "tchau", "tecer", "tédio", "temer",
  "temor", "tempo", "tenaz", "tendo", "tenha", "tenro", "tenso", "tento", "tênue", "termo",
  "terno", "terra", "teste", "tetra", "texto", "tição", "tirar", "tiver", "toada", "tocar",
  "tomar", "toque", "torpe", "torso", "tosco", "traço", "trago", "traje", "trama", "trato",
  "treta", "tribo", "troca", "troça", "troco", "troço", "trupe", "tumba", "turba", "turma",
  "turvo", "tutor", "úbere", "ufano", "úmido", "união", "único", "urdir", "urgir", "usura",
  "vácuo", "vadio", "vagar", "valha", "valia", "valor", "varão", "vário", "vasto", "vazão",
  "vazio", "vedar", "velar", "velho", "veloz", "venal", "vênia", "vento", "verão", "verba",
  "verbo", "verde", "verso", "verve", "vetar", "vetor", "vezes", "vício", "vídeo", "vigia",
  "vigor", "vilão", "virar", "viril", "vírus", "visão", "visar", "vista", "visto", "vital",
  "vivaz", "viver", "volta", "voraz", "vosso", "vulgo", "vulto", "xampu", "xeque", "xucro",
  "zelar", "zumbi"
];
